version: '3'
services:
  web:
    build: .
    ports:
    - "9001:9001"
    links:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - mocroservices

volumes:
  mongodata:

networks:
  mocroservices: